language: python
python:
  - "2.7"
    #- "3.3"    # travis doesn't have apt packages for Python 3
    #- "3.4"

branches:
  only:
    - master

install:
    #- pip install -r requirements.txt
  - sudo apt-get install python-numpy python-scipy
  - pip install karta
  - pip install requests
  - pip install pyproj
  - pip install .

script:
  python tests/runtests.py

