language: python
python:
  - "2.7"
    #- "3.3"    # travis doesn't have apt packages for Python 3
    #- "3.4"

branches:
  only:
    - master

before_install:
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt

install:
    #- pip install -r requirements.txt
  - sudo apt-get update
  - sudo apt-get install python-numpy python-scipy python-pyproj
  - pip install karta
  - pip install requests
  - pip install .

script:
  python tests/runtests.py

